export default function Explore() {
  return (
    <main className="lg:pl-72">
      <div className="xl:pr-96">
        <div className="px-4 py-12  sm:px-6 lg:px-8 flex flex-col justify-center items-center">
          <h1 className="text-4xl font-bold text-primary">Public Experts</h1>
          <h2 className="mt-4 text-gray-500">Explore experts generated by others</h2>
        </div>
      </div>
    </main>
  )
}